-- Criando Tabela de Usuários
CREATE TABLE IF NOT EXISTS tb_users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
cpf VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
password_hash VARCHAR(255) NOT NULL,
created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);
-->===================================================================================================
CREATE UNIQUE INDEX IF NOT EXISTS index_cpf ON tb_users(cpf);
CREATE UNIQUE INDEX IF NOT EXISTS index_email ON tb_users(email);
-->===================================================================================================
-- Criando Tabela Contas
CREATE TABLE IF NOT EXISTS tb_accounts (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
balance NUMERIC(19,2) NOT NULL DEFAULT 0,
user_id BIGINT NOT NULL UNIQUE REFERENCES tb_users(id) ON DELETE CASCADE
);
-->===================================================================================================
-- Criando Tabela de Cobranças
CREATE TABLE IF NOT EXISTS tb_charges (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
origin_id BIGINT NOT NULL REFERENCES tb_users(id) ON DELETE RESTRICT,
destination_id BIGINT NOT NULL REFERENCES tb_users(id) ON DELETE RESTRICT,
amount NUMERIC(19,2) NOT NULL,
description TEXT,
status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
payment_method VARCHAR(20),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
CONSTRAINT chk_charge_status CHECK (status IN ('PENDING','PAID','CANCELED')),
CONSTRAINT chk_payment_method CHECK (payment_method IN ('BALANCE','CARD'))
);
-->===================================================================================================
CREATE INDEX IF NOT EXISTS index_origin_id ON tb_charges(origin_id);
CREATE INDEX IF NOT EXISTS index_destination_id ON tb_charges(destination_id);